// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// BannerGet implements GET /banner operation.
//
// Получение всех баннеров c фильтрацией по фиче и/или
// тегу.
//
// GET /banner
func (UnimplementedHandler) BannerGet(ctx context.Context, params BannerGetParams) (r BannerGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BannerIDDelete implements DELETE /banner/{id} operation.
//
// Удаление баннера по идентификатору.
//
// DELETE /banner/{id}
func (UnimplementedHandler) BannerIDDelete(ctx context.Context, params BannerIDDeleteParams) (r BannerIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BannerIDPatch implements PATCH /banner/{id} operation.
//
// Обновление содержимого баннера.
//
// PATCH /banner/{id}
func (UnimplementedHandler) BannerIDPatch(ctx context.Context, req *BannerIDPatchReq, params BannerIDPatchParams) (r BannerIDPatchRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BannerPost implements POST /banner operation.
//
// Создание нового баннера.
//
// POST /banner
func (UnimplementedHandler) BannerPost(ctx context.Context, req *BannerPostReq) (r BannerPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UserBannerGet implements GET /user_banner operation.
//
// Получение баннера для пользователя.
//
// GET /user_banner
func (UnimplementedHandler) UserBannerGet(ctx context.Context, params UserBannerGetParams) (r UserBannerGetRes, _ error) {
	return r, ht.ErrNotImplemented
}
