// Code generated by ogen, DO NOT EDIT.
package api

type BannerGetRes interface {
	bannerGetRes()
}

type BannerIDDeleteRes interface {
	bannerIDDeleteRes()
}

type BannerIDPatchRes interface {
	bannerIDPatchRes()
}

type BannerPostRes interface {
	bannerPostRes()
}

type UserBannerGetRes interface {
	userBannerGetRes()
}
