// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateBanner implements createBanner operation.
	//
	// Создание нового баннера.
	//
	// POST /banner
	CreateBanner(ctx context.Context, req *CreateBannerRequest) (CreateBannerRes, error)
	// DeleteBanner implements deleteBanner operation.
	//
	// Удаление баннера по идентификатору.
	//
	// DELETE /banner/{id}
	DeleteBanner(ctx context.Context, params DeleteBannerParams) (DeleteBannerRes, error)
	// GetBanner implements getBanner operation.
	//
	// Получение баннера для пользователя.
	//
	// GET /user_banner
	GetBanner(ctx context.Context, params GetBannerParams) (GetBannerRes, error)
	// GetBanners implements getBanners operation.
	//
	// Получение всех баннеров c фильтрацией по фиче и/или
	// тегу.
	//
	// GET /banner
	GetBanners(ctx context.Context, params GetBannersParams) (GetBannersRes, error)
	// SetBanner implements setBanner operation.
	//
	// Обновление содержимого баннера.
	//
	// PATCH /banner/{id}
	SetBanner(ctx context.Context, req *SetBannerRequest, params SetBannerParams) (SetBannerRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
