// Code generated by ogen, DO NOT EDIT.
package api

type CreateBannerRes interface {
	createBannerRes()
}

type DeleteBannerRes interface {
	deleteBannerRes()
}

type GetBannerRes interface {
	getBannerRes()
}

type GetBannersRes interface {
	getBannersRes()
}

type SetBannerRes interface {
	setBannerRes()
}
