// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/jx"
)

type Bearer struct {
	APIKey string
}

// GetAPIKey returns the value of APIKey.
func (s *Bearer) GetAPIKey() string {
	return s.APIKey
}

// SetAPIKey sets the value of APIKey.
func (s *Bearer) SetAPIKey(val string) {
	s.APIKey = val
}

type CreateBannerBadRequest Error

func (*CreateBannerBadRequest) createBannerRes() {}

// CreateBannerForbidden is response for CreateBanner operation.
type CreateBannerForbidden struct{}

func (*CreateBannerForbidden) createBannerRes() {}

type CreateBannerInternalServerError Error

func (*CreateBannerInternalServerError) createBannerRes() {}

// Ref: #/components/schemas/CreateBannerRequest
type CreateBannerRequest struct {
	// Идентификаторы тэгов.
	TagIds []int64 `json:"tag_ids"`
	// Идентификатор фичи.
	FeatureID int64 `json:"feature_id"`
	// Содержимое баннера.
	Content jx.Raw `json:"content"`
	// Флаг активности баннера.
	IsActive bool `json:"is_active"`
}

// GetTagIds returns the value of TagIds.
func (s *CreateBannerRequest) GetTagIds() []int64 {
	return s.TagIds
}

// GetFeatureID returns the value of FeatureID.
func (s *CreateBannerRequest) GetFeatureID() int64 {
	return s.FeatureID
}

// GetContent returns the value of Content.
func (s *CreateBannerRequest) GetContent() jx.Raw {
	return s.Content
}

// GetIsActive returns the value of IsActive.
func (s *CreateBannerRequest) GetIsActive() bool {
	return s.IsActive
}

// SetTagIds sets the value of TagIds.
func (s *CreateBannerRequest) SetTagIds(val []int64) {
	s.TagIds = val
}

// SetFeatureID sets the value of FeatureID.
func (s *CreateBannerRequest) SetFeatureID(val int64) {
	s.FeatureID = val
}

// SetContent sets the value of Content.
func (s *CreateBannerRequest) SetContent(val jx.Raw) {
	s.Content = val
}

// SetIsActive sets the value of IsActive.
func (s *CreateBannerRequest) SetIsActive(val bool) {
	s.IsActive = val
}

// Ref: #/components/schemas/CreateBannerResponse
type CreateBannerResponse struct {
	// Идентификатор созданного баннера.
	BannerID int64 `json:"banner_id"`
}

// GetBannerID returns the value of BannerID.
func (s *CreateBannerResponse) GetBannerID() int64 {
	return s.BannerID
}

// SetBannerID sets the value of BannerID.
func (s *CreateBannerResponse) SetBannerID(val int64) {
	s.BannerID = val
}

func (*CreateBannerResponse) createBannerRes() {}

// CreateBannerUnauthorized is response for CreateBanner operation.
type CreateBannerUnauthorized struct{}

func (*CreateBannerUnauthorized) createBannerRes() {}

type DeleteBannerBadRequest Error

func (*DeleteBannerBadRequest) deleteBannerRes() {}

// DeleteBannerForbidden is response for DeleteBanner operation.
type DeleteBannerForbidden struct{}

func (*DeleteBannerForbidden) deleteBannerRes() {}

type DeleteBannerInternalServerError Error

func (*DeleteBannerInternalServerError) deleteBannerRes() {}

// DeleteBannerNoContent is response for DeleteBanner operation.
type DeleteBannerNoContent struct{}

func (*DeleteBannerNoContent) deleteBannerRes() {}

// DeleteBannerNotFound is response for DeleteBanner operation.
type DeleteBannerNotFound struct{}

func (*DeleteBannerNotFound) deleteBannerRes() {}

// DeleteBannerUnauthorized is response for DeleteBanner operation.
type DeleteBannerUnauthorized struct{}

func (*DeleteBannerUnauthorized) deleteBannerRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *Error) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *Error) SetError(val string) {
	s.Error = val
}

func (*Error) getBannersRes() {}

type GetBannerBadRequest Error

func (*GetBannerBadRequest) getBannerRes() {}

// GetBannerForbidden is response for GetBanner operation.
type GetBannerForbidden struct{}

func (*GetBannerForbidden) getBannerRes() {}

type GetBannerInternalServerError Error

func (*GetBannerInternalServerError) getBannerRes() {}

// GetBannerNotFound is response for GetBanner operation.
type GetBannerNotFound struct{}

func (*GetBannerNotFound) getBannerRes() {}

type GetBannerResponse jx.Raw

func (*GetBannerResponse) getBannerRes() {}

// GetBannerUnauthorized is response for GetBanner operation.
type GetBannerUnauthorized struct{}

func (*GetBannerUnauthorized) getBannerRes() {}

// GetBannersForbidden is response for GetBanners operation.
type GetBannersForbidden struct{}

func (*GetBannersForbidden) getBannersRes() {}

type GetBannersResponse []GetBannersResponseItem

func (*GetBannersResponse) getBannersRes() {}

type GetBannersResponseItem struct {
	// Идентификатор баннера.
	BannerID int64 `json:"banner_id"`
	// Идентификаторы тэгов.
	TagIds []int64 `json:"tag_ids"`
	// Идентификатор фичи.
	FeatureID int64 `json:"feature_id"`
	// Содержимое баннера.
	Content jx.Raw `json:"content"`
	// Флаг активности баннера.
	IsActive bool `json:"is_active"`
	// Дата создания баннера.
	CreatedAt time.Time `json:"created_at"`
	// Дата обновления баннера.
	UpdatedAt OptDateTime `json:"updated_at"`
}

// GetBannerID returns the value of BannerID.
func (s *GetBannersResponseItem) GetBannerID() int64 {
	return s.BannerID
}

// GetTagIds returns the value of TagIds.
func (s *GetBannersResponseItem) GetTagIds() []int64 {
	return s.TagIds
}

// GetFeatureID returns the value of FeatureID.
func (s *GetBannersResponseItem) GetFeatureID() int64 {
	return s.FeatureID
}

// GetContent returns the value of Content.
func (s *GetBannersResponseItem) GetContent() jx.Raw {
	return s.Content
}

// GetIsActive returns the value of IsActive.
func (s *GetBannersResponseItem) GetIsActive() bool {
	return s.IsActive
}

// GetCreatedAt returns the value of CreatedAt.
func (s *GetBannersResponseItem) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *GetBannersResponseItem) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// SetBannerID sets the value of BannerID.
func (s *GetBannersResponseItem) SetBannerID(val int64) {
	s.BannerID = val
}

// SetTagIds sets the value of TagIds.
func (s *GetBannersResponseItem) SetTagIds(val []int64) {
	s.TagIds = val
}

// SetFeatureID sets the value of FeatureID.
func (s *GetBannersResponseItem) SetFeatureID(val int64) {
	s.FeatureID = val
}

// SetContent sets the value of Content.
func (s *GetBannersResponseItem) SetContent(val jx.Raw) {
	s.Content = val
}

// SetIsActive sets the value of IsActive.
func (s *GetBannersResponseItem) SetIsActive(val bool) {
	s.IsActive = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *GetBannersResponseItem) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *GetBannersResponseItem) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

// GetBannersUnauthorized is response for GetBanners operation.
type GetBannersUnauthorized struct{}

func (*GetBannersUnauthorized) getBannersRes() {}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilBool returns new OptNilBool with value set to v.
func NewOptNilBool(v bool) OptNilBool {
	return OptNilBool{
		Value: v,
		Set:   true,
	}
}

// OptNilBool is optional nullable bool.
type OptNilBool struct {
	Value bool
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilBool was set.
func (o OptNilBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilBool) SetTo(v bool) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsSet returns true if value is Null.
func (o OptNilBool) IsNull() bool { return o.Null }

// SetNull sets value to null.
func (o *OptNilBool) SetToNull() {
	o.Set = true
	o.Null = true
	var v bool
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilBool) Get() (v bool, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilInt64 returns new OptNilInt64 with value set to v.
func NewOptNilInt64(v int64) OptNilInt64 {
	return OptNilInt64{
		Value: v,
		Set:   true,
	}
}

// OptNilInt64 is optional nullable int64.
type OptNilInt64 struct {
	Value int64
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilInt64 was set.
func (o OptNilInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilInt64) SetTo(v int64) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsSet returns true if value is Null.
func (o OptNilInt64) IsNull() bool { return o.Null }

// SetNull sets value to null.
func (o *OptNilInt64) SetToNull() {
	o.Set = true
	o.Null = true
	var v int64
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilInt64) Get() (v int64, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilInt64Array returns new OptNilInt64Array with value set to v.
func NewOptNilInt64Array(v []int64) OptNilInt64Array {
	return OptNilInt64Array{
		Value: v,
		Set:   true,
	}
}

// OptNilInt64Array is optional nullable []int64.
type OptNilInt64Array struct {
	Value []int64
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilInt64Array was set.
func (o OptNilInt64Array) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilInt64Array) Reset() {
	var v []int64
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilInt64Array) SetTo(v []int64) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsSet returns true if value is Null.
func (o OptNilInt64Array) IsNull() bool { return o.Null }

// SetNull sets value to null.
func (o *OptNilInt64Array) SetToNull() {
	o.Set = true
	o.Null = true
	var v []int64
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilInt64Array) Get() (v []int64, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilInt64Array) Or(d []int64) []int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type SetBannerBadRequest Error

func (*SetBannerBadRequest) setBannerRes() {}

// SetBannerForbidden is response for SetBanner operation.
type SetBannerForbidden struct{}

func (*SetBannerForbidden) setBannerRes() {}

type SetBannerInternalServerError Error

func (*SetBannerInternalServerError) setBannerRes() {}

// SetBannerNotFound is response for SetBanner operation.
type SetBannerNotFound struct{}

func (*SetBannerNotFound) setBannerRes() {}

// SetBannerOK is response for SetBanner operation.
type SetBannerOK struct{}

func (*SetBannerOK) setBannerRes() {}

// Ref: #/components/schemas/SetBannerRequest
type SetBannerRequest struct {
	// Идентификаторы тэгов.
	TagIds OptNilInt64Array `json:"tag_ids"`
	// Идентификатор фичи.
	FeatureID OptNilInt64 `json:"feature_id"`
	// Содержимое баннера.
	Content jx.Raw `json:"content"`
	// Флаг активности баннера.
	IsActive OptNilBool `json:"is_active"`
}

// GetTagIds returns the value of TagIds.
func (s *SetBannerRequest) GetTagIds() OptNilInt64Array {
	return s.TagIds
}

// GetFeatureID returns the value of FeatureID.
func (s *SetBannerRequest) GetFeatureID() OptNilInt64 {
	return s.FeatureID
}

// GetContent returns the value of Content.
func (s *SetBannerRequest) GetContent() jx.Raw {
	return s.Content
}

// GetIsActive returns the value of IsActive.
func (s *SetBannerRequest) GetIsActive() OptNilBool {
	return s.IsActive
}

// SetTagIds sets the value of TagIds.
func (s *SetBannerRequest) SetTagIds(val OptNilInt64Array) {
	s.TagIds = val
}

// SetFeatureID sets the value of FeatureID.
func (s *SetBannerRequest) SetFeatureID(val OptNilInt64) {
	s.FeatureID = val
}

// SetContent sets the value of Content.
func (s *SetBannerRequest) SetContent(val jx.Raw) {
	s.Content = val
}

// SetIsActive sets the value of IsActive.
func (s *SetBannerRequest) SetIsActive(val OptNilBool) {
	s.IsActive = val
}

// SetBannerUnauthorized is response for SetBanner operation.
type SetBannerUnauthorized struct{}

func (*SetBannerUnauthorized) setBannerRes() {}
