// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateBanner implements createBanner operation.
//
// Создание нового баннера.
//
// POST /banner
func (UnimplementedHandler) CreateBanner(ctx context.Context, req *CreateBannerRequest) (r CreateBannerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteBanner implements deleteBanner operation.
//
// Удаление баннера по идентификатору.
//
// DELETE /banner/{id}
func (UnimplementedHandler) DeleteBanner(ctx context.Context, params DeleteBannerParams) (r DeleteBannerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBanner implements getBanner operation.
//
// Получение баннера для пользователя.
//
// GET /user_banner
func (UnimplementedHandler) GetBanner(ctx context.Context, params GetBannerParams) (r GetBannerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBanners implements getBanners operation.
//
// Получение всех баннеров c фильтрацией по фиче и/или
// тегу.
//
// GET /banner
func (UnimplementedHandler) GetBanners(ctx context.Context, params GetBannersParams) (r GetBannersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetBanner implements setBanner operation.
//
// Обновление содержимого баннера.
//
// PATCH /banner/{id}
func (UnimplementedHandler) SetBanner(ctx context.Context, req *SetBannerRequest, params SetBannerParams) (r SetBannerRes, _ error) {
	return r, ht.ErrNotImplemented
}
