name: build and test

on:
  push:
    branches: [ main, dev]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.2

    - name: Build
      run: go build -v ./...

    - name: Prepare integration test environment
      uses: hoverkraft-tech/compose-action@v2.0.0
      with:
        compose-file: "./docker-compose-test.yml"
      env: 
        DB_TEST_HOST: db-test
        DB_PORT: 5433
        DB_NAME: banners_db
        DB_USER: postgres
        DB_PASSWORD: banners_pass
        DB_SSL: disable
        REDIS_PORT: 6379
    - name: Sleep for 5 seconds
      run: sleep 5s
    - name: Unit tests
      run: go test -v -race -covermode=atomic -tags=unit -cover ./... -args -test.gocoverdir="${{ github.workspace }}/coverage/unit/" 
    - name: Integration tests
      run: go test -v -race -covermode=atomic -tags=integration -cover ./... -args -test.gocoverdir="${{ github.workspace }}/coverage/integration/"
    - name: Compute coverage
      run: go tool covdata textfmt -i=./coverage/unit,./coverage/integration -o coverage/profile && rm ./coverage/unit/* && rm ./coverage/integration/*
    - name: Test coverage
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true 
        files: ./coverage/profile
        name: codecov-umbrella 
        token: ${{ secrets.CODECOV_TOKEN }} 
        verbose: true 
        slug: nikitads9/banner-service-api
