name: build and test

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.2

    - name: Build
      run: go build -v ./...

    - name: Integration tests
      run: make run-integration-tests
    -
      run: go test -v -race -coverprofile="coverage.out" -covermode=atomic ./internal
    - name: Test coverage
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true 
        files: ./coverage.out
        flags: unittests 
        name: codecov-umbrella 
        token: ${{ secrets.CODECOV_TOKEN }} 
        verbose: true 
        slug: nikitads9/banner-service-api
