name: linters

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
    linter:
        strategy:
          matrix:
            go-version: [1.22.x]
            os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
        - name: Install Go
          uses: actions/setup-go@v5
          with:
            go-version: ${{ matrix.go-version }}
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Run linters
          uses: golangci/golangci-lint-action@v4
          with:
            version: latest